### ISSUE TITLE
About Direction Finding

### ISSUE THREAD

**Issue by JiruiLiu** [openai/automated-interpretability#12]
Dear authors， do you plan to open source the “Finding explainable directions” part of the code in the future? Thanks.

**Comment by redknight99** [comment]
Sorry to bother, could you link to the "Finding explainable directions" part in the Repo? I would like to understand the question better. Thank you.

**Comment by WuTheFWasThat** [comment]
they are referring to https://openaipublic.blob.core.windows.net/neuron-explainer/paper/index.html#sec-direction-finding

we don't plan to open source this
