### ISSUE TITLE
Installing neuron-explainer doesn't seem to work.

### ISSUE THREAD

**Issue by HoagyC** [openai/automated-interpretability#13]
If I run `pip install "git+https://github.com/openai/automated-interpretability.git#subdirectory=neuron-explainer"` I understand that this should install the repo as part of my environment, but it only installs a select few of the required files. Is there something wrong with the setup.py?
```
# installed-files.txt
../neuron_explainer/__init__.py
../neuron_explainer/__pycache__/__init__.cpython-39.pyc
../neuron_explainer/__pycache__/api_client.cpython-39.pyc
../neuron_explainer/api_client.py
PKG-INFO
SOURCES.txt
dependency_links.txt
requires.txt
top_level.txt
```

**Comment by WuTheFWasThat** [comment]
try again, hopefully fixed now!

**Comment by HoagyC** [comment]
Works great, cheers!
