### ISSUE TITLE
Dataset for neuron activation

### ISSUE THREAD

**Issue by Peanuttttttttt** [openai/automated-interpretability#19]
Hi.

I am wondering where can I get all the random samples you used to calculate the activation, instead of opening tens of thousands of JSON files to get them. I am trying to use the same random samples on other LLMs. 

Thanks.

**Comment by BiEchi** [comment]
You can try use a script to download all the JSONs with a Python script.

**Comment by clclclaiggg** [comment]
你好，能分享一下脚本吗？谢谢您

**Comment by clclclaiggg** [comment]
Hello, can you share the script? Thank you.
